apiVersion: v1
kind: Service
metadata:
  name:  hkdevops-rtp-service
  namespace: hkdevops
spec:
  type: NodePort
  selector:
    app: hkdevops-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000